import AppKit
import ApplicationServices
import Observation

/// Clipboard history. There is no change notification for `NSPasteboard`, so the general
/// pasteboard's `changeCount` is polled; items flagged as concealed (password managers)
/// or transient are ignored.
@Observable
final class ClipboardStore {
    private(set) var entries: [ClipEntry] = []

    func applyDemo(_ demo: [ClipEntry]) { entries = demo }
    var query: String = ""

    private let indexURL = Paths.file("clipboard.json")
    private let imagesDir = Paths.directory("Clipboard")
    private let pasteboard = NSPasteboard.general
    private var lastChangeCount: Int
    private var timer: Timer?
    /// Set while we write to the pasteboard ourselves so the write is not re-recorded.
    private var selfWriteCount = -1

    var filtered: [ClipEntry] {
        let trimmed = query.trimmingCharacters(in: .whitespaces)
        let sorted = entries.sorted { ($0.pinned ? 1 : 0, $0.createdAt) > ($1.pinned ? 1 : 0, $1.createdAt) }
        guard !trimmed.isEmpty else { return sorted }
        return sorted.filter { $0.preview.localizedCaseInsensitiveContains(trimmed) }
    }

    init() {
        lastChangeCount = NSPasteboard.general.changeCount
        entries = JSONStore.load([ClipEntry].self, from: indexURL) ?? []
    }

    // MARK: - Monitoring

    func start() {
        guard timer == nil else { return }
        let timer = Timer(timeInterval: 0.4, repeats: true) { _ in
            MainActor.assumeIsolated { self.poll() }
        }
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    private func poll() {
        guard !Debug.isDemo else { return }
        guard Preferences.shared.clipboardEnabled else { return }
        let count = pasteboard.changeCount
        guard count != lastChangeCount else { return }
        lastChangeCount = count
        guard count != selfWriteCount else { return }
        guard !isConcealed else { return }
        capture()
    }

    /// Conventions honoured by password managers and clipboard tools.
    private var isConcealed: Bool {
        let types = pasteboard.types?.map(\.rawValue) ?? []
        let markers = ["org.nspasteboard.ConcealedType",
                       "org.nspasteboard.TransientType",
                       "org.nspasteboard.AutoGeneratedType",
                       "com.agilebits.onepassword"]
        return types.contains { markers.contains($0) }
    }

    private func capture() {
        if let string = pasteboard.string(forType: .string),
           !string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            let options: [NSPasteboard.ReadingOptionKey: Any] = [.urlReadingFileURLsOnly: true]
            if let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: options) as? [URL],
               let first = urls.first {
                append(ClipEntry(id: UUID(), kind: .fileURL, text: first.path,
                                 imageName: nil, createdAt: Date(), pinned: false))
            } else {
                append(ClipEntry(id: UUID(), kind: .text, text: string,
                                 imageName: nil, createdAt: Date(), pinned: false))
            }
            return
        }

        if let image = NSImage(pasteboard: pasteboard),
           let png = image.pngData {
            let name = "\(UUID().uuidString).png"
            try? png.write(to: imagesDir.appendingPathComponent(name), options: .atomic)
            append(ClipEntry(id: UUID(), kind: .image, text: nil,
                             imageName: name, createdAt: Date(), pinned: false))
        }
    }

    // MARK: - Mutation

    private func append(_ entry: ClipEntry) {
        // Collapse an immediate repeat of the same text.
        if let first = entries.first, first.kind == entry.kind, first.text == entry.text,
           entry.kind != .image {
            return
        }
        entries.insert(entry, at: 0)
        trim()
        persist()
    }

    func copy(_ entry: ClipEntry) {
        pasteboard.clearContents()
        switch entry.kind {
        case .text:
            pasteboard.setString(entry.text ?? "", forType: .string)
        case .fileURL:
            let url = URL(fileURLWithPath: entry.text ?? "")
            pasteboard.writeObjects([url as NSURL])
        case .image:
            if let name = entry.imageName,
               let image = NSImage(contentsOf: imagesDir.appendingPathComponent(name)) {
                pasteboard.writeObjects([image])
            }
        }
        selfWriteCount = pasteboard.changeCount
        lastChangeCount = selfWriteCount
    }

    /// Puts the entry on the pasteboard and sends ⌘V to whatever is frontmost.
    ///
    /// Notchbase never becomes the active app, so the target application is still focused —
    /// synthesising the keystroke is enough. Posting events needs Accessibility permission.
    func paste(_ entry: ClipEntry) -> Bool {
        copy(entry)
        guard Self.canPostEvents(prompt: true) else { return false }
        Task {
            // Let the pasteboard settle before the keystroke arrives.
            try? await Task.sleep(for: .milliseconds(120))
            Self.sendCommandV()
        }
        return true
    }

    static func canPostEvents(prompt: Bool) -> Bool {
        let options = ["AXTrustedCheckOptionPrompt": prompt]
        return AXIsProcessTrustedWithOptions(options as CFDictionary)
    }

    private static func sendCommandV() {
        let source = CGEventSource(stateID: .combinedSessionState)
        let v: CGKeyCode = 9
        guard let down = CGEvent(keyboardEventSource: source, virtualKey: v, keyDown: true),
              let up = CGEvent(keyboardEventSource: source, virtualKey: v, keyDown: false)
        else { return }
        down.flags = .maskCommand
        up.flags = .maskCommand
        down.post(tap: .cghidEventTap)
        up.post(tap: .cghidEventTap)
    }

    func togglePin(_ entry: ClipEntry) {
        guard let index = entries.firstIndex(where: { $0.id == entry.id }) else { return }
        entries[index].pinned.toggle()
        persist()
    }

    func remove(_ entry: ClipEntry) {
        if let name = entry.imageName {
            try? FileManager.default.removeItem(at: imagesDir.appendingPathComponent(name))
        }
        entries.removeAll { $0.id == entry.id }
        persist()
    }

    func clear() {
        for entry in entries where !entry.pinned {
            if let name = entry.imageName {
                try? FileManager.default.removeItem(at: imagesDir.appendingPathComponent(name))
            }
        }
        entries.removeAll { !$0.pinned }
        persist()
    }

    func image(for entry: ClipEntry) -> NSImage? {
        guard let name = entry.imageName else { return nil }
        return NSImage(contentsOf: imagesDir.appendingPathComponent(name))
    }

    private func trim() {
        let limit = max(20, Preferences.shared.clipboardLimit)
        var unpinned = entries.filter { !$0.pinned }
        guard unpinned.count > limit else { return }
        let doomed = unpinned.suffix(unpinned.count - limit)
        for entry in doomed {
            if let name = entry.imageName {
                try? FileManager.default.removeItem(at: imagesDir.appendingPathComponent(name))
            }
        }
        let ids = Set(doomed.map(\.id))
        entries.removeAll { ids.contains($0.id) }
        unpinned.removeAll()
    }

    private func persist() {
        JSONStore.save(entries, to: indexURL)
    }
}

extension NSImage {
    var pngData: Data? {
        guard let tiff = tiffRepresentation,
              let rep = NSBitmapImageRep(data: tiff) else { return nil }
        return rep.representation(using: .png, properties: [:])
    }
}
